CREATE TABLESPACE ad_DATA
DATAFILE 'C:/app/sam/oradata/lab00sammy/adData01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
  
CREATE TABLESPACE ad_INDX
DATAFILE 'C:/app/sam/oradata/lab00sammy/adIndx01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE USER ad    
IDENTIFIED BY ad
DEFAULT TABLESPACE ad_data
QUOTA 10M ON ad_data
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;
  
CREATE ROLE ad
IDENTIFIED BY ad;
  
GRANT CONNECT TO ad;
GRANT CREATE TABLE TO ad;
