--Indique la cantidad total de empleados por departamento

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, count(1) AS TOTAL
FROM EMPLOYEE E INNER JOIN DEPARTMENT D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;


SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
--12 22 33 42
