--CREE 10 CLIENTES

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (1, 'LARRY', 'VARGAS', 89875465);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (2, 'SAMANTHA', 'VILLALOBOS', 89871234);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (3, 'BERNARDO', 'ARBUROLA', 22875465);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (4, 'BENEDICTO', 'BARRANTES', 22505465);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (5, 'ADRIANA', 'ALVAREZ', 85013591);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (6, 'MARIELA', 'VARGAS', 22941234);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (7, 'MELISSA', 'CALDERON', 22924554);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (8, 'FABIAN', 'LOPEZ', 27305098);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (9, 'JAZMIN', 'OBANDO', 83073472);

INSERT INTO CUSTOMER(CUSTOMER_ID, NOMBRE, APELLIDO, TELEFONO)
VALUES (10, 'MARISOL', 'CAMPOS', 88706490);
